### ISSUE TITLE
pip install fails unless requets

### ISSUE THREAD

**Issue by wjdp** [clubhouse/clubhouse-lib#74]
If you don't have requests already installed you get the following

```
Collecting requests==2.23.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting attrs==19.3.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting certifi==2020.4.5.2
  Using cached certifi-2020.4.5.2-py2.py3-none-any.whl (157 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting clubhouse-lib==1.0.0
  Using cached clubhouse-lib-1.0.0.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/will/.virtualenvs/clubhub2/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/will/pip-install-uesiswx1/clubhouse-lib/setup.py'"'"'; __file__='"'"'/tmp/will/pip-install-uesiswx1/clubhouse-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/will/pip-pip-egg-info-hzuqziq0
         cwd: /tmp/will/pip-install-uesiswx1/clubhouse-lib/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/will/pip-install-uesiswx1/clubhouse-lib/setup.py", line 6, in <module>
        import clubhouse_lib
      File "/tmp/will/pip-install-uesiswx1/clubhouse-lib/clubhouse_lib/__init__.py", line 4, in <module>
        from clubhouse_lib.client import ClubhouseClient
      File "/tmp/will/pip-install-uesiswx1/clubhouse-lib/clubhouse_lib/client.py", line 3, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Seeing on python 3.6 and 3.8.

This happens even if you have requests higher up in `requirements.txt` than `clubhouse_lib`.

This prevents using this library on a service like heroku where you have less control and only get one run of `pip install`.

**Comment by wjdp** [comment]
Apologies wrong repo / lib :smile:
